# backend/serverless.yml
service: express-lambda-service

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-offline
  - serverless-http
