

const applications = [
  'Facebook',
  'Twitter',
  'Instagram',
  'LinkedIn',
  'Snapchat',
  'Pinterest',
  'Reddit',
  'TikTok',
  'WhatsApp',
  'YouTube',
  'Amazon',
  'Google Maps',
  'Spotify',
  'Netflix',
  'Zoom',
  'Skype',
  'Slack',
  'Microsoft Teams',
  'Dropbox',
  'Gmail',
  'Outlook',
  'Yahoo Mail',
  'Apple Music',
  'SoundCloud',
  'Hulu',
  'Disney+',
  'Prime Video',
  'Uber',
  'Lyft',
  'Airbnb',
  'Booking.com',
  'Expedia',
  'TripAdvisor',
  'Waze',
  'Yelp',
  'Foursquare',
  'Venmo',
  'PayPal',
  'Cash App',
  'Zelle',
  'Google Pay',
  'Apple Pay',
  'Samsung Pay',
  'eBay',
  'Etsy',
  'Shopify',
  'Walmart',
  'Target',
  'Best Buy',
  'Costco',
  'Home Depot',
  'Lowe\'s',
  'AliExpress',
  'WeChat',
  'QQ',
  'Telegram',
  'Signal',
  'Viber',
  'LINE',
  'KakaoTalk',
  'Messenger',
  'Tumblr',
  'Flickr',
  'Weibo',
  'Quora',
  'Medium',
  'WordPress',
  'Blogger',
  'Redfin',
  'Zillow',
  'Trulia',
  'Mint',
  'Robinhood',
  'E*TRADE',
  'TD Ameritrade',
  'Coinbase',
  'Binance',
  'Kraken',
  'Bitfinex',
  'MetaMask',
  'Trust Wallet',
  'BlockFi',
  'Nexo',
  'Chime',
  'SoFi',
  'Betterment',
  'Acorns',
  'Wealthfront',
  'Credit Karma',
  'Experian',
  'TransUnion',
  'Equifax',
  'Tinder',
  'Bumble',
  'Hinge',
  'OkCupid',
  'Match',
  'Plenty of Fish',
  'Grindr',
  'Her',
  'Coffee Meets Bagel',
  'Happn',
  'Meetup',
  'Eventbrite',
  'Ticketmaster',
  'StubHub',
  'Fandango',
  'AMC Theatres',
  'Regal Cinemas',
  'Cinemark',
  'Alamo Drafthouse',
  'Netflix DVD',
  'Shazam',
  'SoundHound',
  'TuneIn Radio',
  'iHeartRadio',
  'Audible',
  'Goodreads',
  'Kindle',
  'Nook',
  'Google Play Books',
  'Apple Books',
  'OverDrive',
  'Libby',
  'Hoopla',
  'Duolingo',
  'Rosetta Stone',
  'Babbel',
  'Memrise',
  'Busuu',
  'HelloTalk',
  'Tandem',
  'Coursera',
  'Udemy',
  'edX',
  'Khan Academy',
  'Skillshare',
  'MasterClass',
  'LinkedIn Learning',
  'Codecademy',
  'Pluralsight',
  'Udacity',
  'DataCamp',
  'Coursera',
  'Brilliant',
  'CliffsNotes',
  'SparkNotes',
  'Quizlet',
  'Anki',
  'Chegg',
  'Kahoot!',
  'Socrative',
  'ClassDojo',
  'Remind',
  'Google Classroom',
  'Microsoft OneNote',
  'Evernote',
  'Notion',
  'Trello',
  'Asana',
  'Jira',
  'Monday.com',
  'Basecamp',
  'Wrike',
  'Smartsheet',
  'Airtable',
  'ClickUp',
  'Miro',
  'Lucidchart',
  'Canva',
  'Adobe Spark',
  'Adobe Photoshop',
  'Adobe Illustrator',
  'CorelDRAW',
  'Affinity Designer',
  'Procreate',
  'Sketch',
  'Figma',
  'InVision',
  'Marvel',
  'Balsamiq',
  'Axure RP',
  'MockFlow',
  'Moqups',
  'Framer',
  'Zeplin',
  'Abstract',
  'Inkscape',
  'GIMP',
  'Paint.NET',
  'Blender',
  'Autodesk Maya',
  '3ds Max',
  'Cinema 4D',
  'SketchUp',
  'ZBrush',
  'Unity',
  'Unreal Engine',
  'Godot',
  'CryEngine',
  'RPG Maker',
  'GameMaker Studio',
  'Construct',
  'Twine',
  'Ren\'Py',
  'Stencyl',
  'Lumberyard',
  'AppGameKit',
  'Buildbox',
  'Corona SDK',
  'Fusion 360',
  'SolidWorks',
  'AutoCAD',
  'Revit',
  'ArchiCAD',
  'Chief Architect',
  'SketchUp Pro',
  'Vectorworks',
  'Allplan',
  'BricsCAD',
  'Civil 3D',
  'MicroStation',
  'STAAD Pro',
  'ETABS',
  'SAFE',
  'SAP2000',
  'CSiBridge',
  'Tekla Structures',
  'Robot Structural Analysis',
  'Sage 300'
];

export default applications;