

const applications = {
  // Personal Accounts
  'Facebook': 'Personal Accounts',
  'Twitter': 'Personal Accounts',
  'Instagram': 'Personal Accounts',
  'LinkedIn': 'Personal Accounts',
  'Snapchat': 'Personal Accounts',
  'Pinterest': 'Personal Accounts',
  'Reddit': 'Personal Accounts',
  'TikTok': 'Personal Accounts',
  'WhatsApp': 'Personal Accounts',
  'Gmail': 'Personal Accounts',
  'Yahoo Mail': 'Personal Accounts',
  'Apple Music': 'Personal Accounts',
  'SoundCloud': 'Personal Accounts',
  'WeChat': 'Personal Accounts',
  'QQ': 'Personal Accounts',
  'Telegram': 'Personal Accounts',
  'Signal': 'Personal Accounts',
  'Viber': 'Personal Accounts',
  'LINE': 'Personal Accounts',
  'KakaoTalk': 'Personal Accounts',
  'Messenger': 'Personal Accounts',
  'Tumblr': 'Personal Accounts',
  'Flickr': 'Personal Accounts',
  'Weibo': 'Personal Accounts',
  'Quora': 'Personal Accounts',
  'Medium': 'Personal Accounts',
  'WordPress': 'Personal Accounts',
  'Blogger': 'Personal Accounts',
  'Venmo': 'Personal Accounts',
  'Cash App': 'Personal Accounts',
  'Tinder': 'Personal Accounts',
  'Bumble': 'Personal Accounts',
  'Hinge': 'Personal Accounts',
  'OkCupid': 'Personal Accounts',
  'Match': 'Personal Accounts',
  'Plenty of Fish': 'Personal Accounts',
  'Grindr': 'Personal Accounts',
  'Her': 'Personal Accounts',
  'Coffee Meets Bagel': 'Personal Accounts',
  'Happn': 'Personal Accounts',
  'Meetup': 'Personal Accounts',
  'Eventbrite': 'Personal Accounts',
  'Goodreads': 'Personal Accounts',
  'Kindle': 'Personal Accounts',
  'Nook': 'Personal Accounts',
  'Google Play Books': 'Personal Accounts',
  'Apple Books': 'Personal Accounts',
  'OverDrive': 'Personal Accounts',
  'Libby': 'Personal Accounts',
  'Hoopla': 'Personal Accounts',
  'Mint': 'Personal Accounts',
  'Credit Karma': 'Personal Accounts',
  'Experian': 'Personal Accounts',
  'TransUnion': 'Personal Accounts',
  'Equifax': 'Personal Accounts',
  'Duolingo': 'Personal Accounts',
  'Rosetta Stone': 'Personal Accounts',
  'Babbel': 'Personal Accounts',
  'Memrise': 'Personal Accounts',
  'Busuu': 'Personal Accounts',
  'HelloTalk': 'Personal Accounts',
  'Tandem': 'Personal Accounts',
  'Coursera': 'Personal Accounts',
  'Udemy': 'Personal Accounts',
  'edX': 'Personal Accounts',
  'Khan Academy': 'Personal Accounts',
  'Skillshare': 'Personal Accounts',
  'MasterClass': 'Personal Accounts',
  'LinkedIn Learning': 'Personal Accounts',
  'Codecademy': 'Personal Accounts',
  'Pluralsight': 'Personal Accounts',
  'Udacity': 'Personal Accounts',
  'DataCamp': 'Personal Accounts',
  'Brilliant': 'Personal Accounts',
  'CliffsNotes': 'Personal Accounts',
  'SparkNotes': 'Personal Accounts',
  'Quizlet': 'Personal Accounts',
  'Anki': 'Personal Accounts',
  'Chegg': 'Personal Accounts',
  'Kahoot!': 'Personal Accounts',
  'Socrative': 'Personal Accounts',
  'ClassDojo': 'Personal Accounts',
  'Remind': 'Personal Accounts',
  'Google Classroom': 'Personal Accounts',
  'Shazam': 'Personal Accounts',
  'SoundHound': 'Personal Accounts',
  'TuneIn Radio': 'Personal Accounts',
  'iHeartRadio': 'Personal Accounts',
  'Audible': 'Personal Accounts',
  'Microsoft OneNote': 'Personal Accounts',
  'Evernote': 'Personal Accounts',
  'Notion': 'Personal Accounts',
  'Redfin': 'Personal Accounts',
  'Zillow': 'Personal Accounts',
  'Trulia': 'Personal Accounts',

  // Work Accounts
  'Zoom': 'Work Accounts',
  'Skype': 'Work Accounts',
  'Slack': 'Work Accounts',
  'Microsoft Teams': 'Work Accounts',
  'Dropbox': 'Work Accounts',
  'Outlook': 'Work Accounts',
  'Trello': 'Work Accounts',
  'Asana': 'Work Accounts',
  'Jira': 'Work Accounts',
  'Monday.com': 'Work Accounts',
  'Basecamp': 'Work Accounts',
  'Wrike': 'Work Accounts',
  'Smartsheet': 'Work Accounts',
  'Airtable': 'Work Accounts',
  'ClickUp': 'Work Accounts',
  'Miro': 'Work Accounts',
  'Lucidchart': 'Work Accounts',
  'Canva': 'Work Accounts',
  'Adobe Spark': 'Work Accounts',
  'Adobe Photoshop': 'Work Accounts',
  'Adobe Illustrator': 'Work Accounts',
  'CorelDRAW': 'Work Accounts',
  'Affinity Designer': 'Work Accounts',
  'Sketch': 'Work Accounts',
  'Figma': 'Work Accounts',
  'InVision': 'Work Accounts',
  'Marvel': 'Work Accounts',
  'Balsamiq': 'Work Accounts',
  'Axure RP': 'Work Accounts',
  'MockFlow': 'Work Accounts',
  'Moqups': 'Work Accounts',
  'Framer': 'Work Accounts',
  'Zeplin': 'Work Accounts',
  'Abstract': 'Work Accounts',
  'Inkscape': 'Work Accounts',
  'GIMP': 'Work Accounts',
  'Paint.NET': 'Work Accounts',
  'Blender': 'Work Accounts',
  'Autodesk Maya': 'Work Accounts',
  '3ds Max': 'Work Accounts',
  'Cinema 4D': 'Work Accounts',
  'SketchUp': 'Work Accounts',
  'ZBrush': 'Work Accounts',
  'Unity': 'Work Accounts',
  'Unreal Engine': 'Work Accounts',
  'Godot': 'Work Accounts',
  'CryEngine': 'Work Accounts',
  'RPG Maker': 'Work Accounts',
  'GameMaker Studio': 'Work Accounts',
  'Construct': 'Work Accounts',
  'Twine': 'Work Accounts',
  'Ren\'Py': 'Work Accounts',
  'Stencyl': 'Work Accounts',
  'Lumberyard': 'Work Accounts',
  'AppGameKit': 'Work Accounts',
  'Buildbox': 'Work Accounts',
  'Corona SDK': 'Work Accounts',
  'Fusion 360': 'Work Accounts',
  'SolidWorks': 'Work Accounts',
  'AutoCAD': 'Work Accounts',
  'Revit': 'Work Accounts',
  'ArchiCAD': 'Work Accounts',
  'Chief Architect': 'Work Accounts',
  'SketchUp Pro': 'Work Accounts',
  'Vectorworks': 'Work Accounts',
  'Allplan': 'Work Accounts',
  'BricsCAD': 'Work Accounts',
  'Civil 3D': 'Work Accounts',
  'MicroStation': 'Work Accounts',
  'STAAD Pro': 'Work Accounts',
  'ETABS': 'Work Accounts',
  'SAFE': 'Work Accounts',
  'SAP2000': 'Work Accounts',
  'CSiBridge': 'Work Accounts',
  'Tekla Structures': 'Work Accounts',
  'Robot Structural Analysis': 'Work Accounts',
  'Sage 300': 'Work Accounts',

  // Banking and Finance
  'PayPal': 'Banking and Finance',
  'Zelle': 'Banking and Finance',
  'Google Pay': 'Banking and Finance',
  'Apple Pay': 'Banking and Finance',
  'Samsung Pay': 'Banking and Finance',
  'Robinhood': 'Banking and Finance',
  'E*TRADE': 'Banking and Finance',
  'TD Ameritrade': 'Banking and Finance',
  'Coinbase': 'Banking and Finance',
  'Binance': 'Banking and Finance',
  'Kraken': 'Banking and Finance',
  'Bitfinex': 'Banking and Finance',
  'MetaMask': 'Banking and Finance',
  'Trust Wallet': 'Banking and Finance',
  'BlockFi': 'Banking and Finance',
  'Nexo': 'Banking and Finance',
  'Chime': 'Banking and Finance',
  'SoFi': 'Banking and Finance',
  'Betterment': 'Banking and Finance',
  'Acorns': 'Banking and Finance',
  'Wealthfront': 'Banking and Finance',
  'Bank of America': 'Banking and Finance',
  'Chase': 'Banking and Finance',
  'Wells Fargo': 'Banking and Finance',
  'Citibank': 'Banking and Finance',
  'Capital One': 'Banking and Finance',
  'American Express': 'Banking and Finance',

  // Shopping
  'Amazon': 'Shopping',
  'eBay': 'Shopping',
  'Etsy': 'Shopping',
  'Shopify': 'Shopping',
  'Walmart': 'Shopping',
  'Target': 'Shopping',
  'Best Buy': 'Shopping',
  'Costco': 'Shopping',
  'Home Depot': 'Shopping',
  'Lowe\'s': 'Shopping',
  'AliExpress': 'Shopping',
  'Wayfair': 'Shopping',
  'Macy\'s': 'Shopping',
  'IKEA': 'Shopping',
  'Kohl\'s': 'Shopping',
  'Sephora': 'Shopping',
  'Nordstrom': 'Shopping',
  'Newegg': 'Shopping',
  'Overstock': 'Shopping',

  // Subscriptions
  'Spotify': 'Subscriptions',
  'Netflix': 'Subscriptions',
  'Hulu': 'Subscriptions',
  'Disney+': 'Subscriptions',
  'Prime Video': 'Subscriptions',
  'HBO Max': 'Subscriptions',
  'Apple TV+': 'Subscriptions',

  // Utilities
  'AT&T': 'Utilities',
  'Verizon': 'Utilities',
  'Comcast': 'Utilities',
  'Spectrum': 'Utilities',
  'Xfinity': 'Utilities',
  'Direct Energy': 'Utilities',
  'Duke Energy': 'Utilities',
  'PG&E': 'Utilities',
  'Con Edison': 'Utilities',
  'British Gas': 'Utilities',
  'Npower': 'Utilities',
  'EDF Energy': 'Utilities',
  'Scottish Power': 'Utilities',

  // Travel
  'Uber': 'Travel',
  'Lyft': 'Travel',
  'Airbnb': 'Travel',
  'Booking.com': 'Travel',
  'Expedia': 'Travel',
  'Kayak': 'Travel',
  'Skyscanner': 'Travel',
  'TripAdvisor': 'Travel',
  'Travelocity': 'Travel',
  'Orbitz': 'Travel',
  'Hotels.com': 'Travel',
  'Priceline': 'Travel',
  'Agoda': 'Travel',

  // Health
  'MyChart': 'Health',
  'Teladoc': 'Health',
  'Amwell': 'Health',
  'Zocdoc': 'Health',
  'WebMD': 'Health',
  'Fitbit': 'Health',
  'Garmin Connect': 'Health',
  'Strava': 'Health',
  'Nike Training Club': 'Health',
  'Peloton': 'Health',

  // Entertainment
  'Steam': 'Entertainment',
  'Xbox Live': 'Entertainment',
  'PlayStation Network': 'Entertainment',
  'Nintendo Switch Online': 'Entertainment',
  'Epic Games Store': 'Entertainment',
  'Humble Bundle': 'Entertainment',
  'Twitch': 'Entertainment',
  'YouTube': 'Entertainment',
  'Fandango': 'Entertainment',
  'AMC Theatres': 'Entertainment',
  'Regal Cinemas': 'Entertainment',
  'Ticketmaster': 'Entertainment',
  'Live Nation': 'Entertainment',
  'StubHub': 'Entertainment',
  'Eventbrite': 'Entertainment',
  'Meetup': 'Entertainment',
};


export default applications;